name: Lint code

on: [pull_request]

# todo: add caching
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Installing dependencies
        run: yarn

      - name: Linting code
        run: yarn lint
